def preprocess_new_data(data):
    X = [[data.total_property_area,
                    data.state_of_the_building,
                    data.number_of_facades,
                    data.number_of_bedrooms,
                    1 if data.province == "Antwerp" else 0,
                    1 if data.province == "Brussels" else 0,
                    1 if data.province == "East_Flanders" else 0,
                    1 if data.province == "Flemish_Brabant" else 0,
                    1 if data.province == "Walloon_Brabant" else 0,
                    1 if data.province == "Hainaut" else 0,
                    1 if data.province == "Limburg" else 0,
                    1 if data.province == "Liège" else 0,
                    1 if data.province == "Luxembourg" else 0,
                    1 if data.province == "Namur" else 0,
                    1 if data.province == "West_Flanders" else 0,
                    1 if data.subtype == "APARTMENT" else 0,
                    1 if data.subtype == "APARTMENT_BLOCK" else 0,
                    1 if data.subtype == "BUNGALOW" else 0,
                    1 if data.subtype == "CASTLE" else 0,
                    1 if data.subtype == "CHALET" else 0,
                    1 if data.subtype == "COUNTRY_COTTAGE" else 0,
                    1 if data.subtype == "DUPLEX" else 0,
                    1 if data.subtype == "EXCEPTIONAL_PROPERTY" else 0,
                    1 if data.subtype == "FARMHOUSE" else 0,
                    1 if data.subtype == "FLAT_STUDIO" else 0,
                    1 if data.subtype == "GROUND_FLOOR" else 0,
                    1 if data.subtype == "HOUSE" else 0,
                    1 if data.subtype == "KOT" else 0,
                    1 if data.subtype == "LOFT" else 0,
                    1 if data.subtype == "MANOR_HOUSE" else 0,
                    1 if data.subtype == "MANSION" else 0,
                    1 if data.subtype == "MIXED_USE_BUILDING" else 0,
                    1 if data.subtype == "OTHER_PROPERTY" else 0,
                    1 if data.subtype == "PENTHOUSE" else 0,
                    1 if data.subtype == "SERVICE_FLAT" else 0,
                    1 if data.subtype == "TOWN_HOUSE" else 0,
                    1 if data.subtype == "TRIPLEX" else 0,
                    1 if data.subtype == "VILLA" else 0,
                    data.furnished,
                    data.open_fire,
                    data.terrace,
                    data.garden,
                    data.swimming_pool
                    ]]
    return X
